name: glucose-alerts

services:
  signal-api:
    image: bbernhard/signal-cli-rest-api
    restart: unless-stopped
    volumes:
      - signal-data:/home/.local/share/signal-cli
    environment:
      MODE: native
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

  glucose-alerts:
    image: ghcr.io/drigberg/glucose-alerts:latest
    command: ["bash", "./scripts/run-every-minute.sh"]
    init: true
    restart: unless-stopped
    env_file: ../.env
    volumes:
      - glucose-data:/app/data
    depends_on:
      - signal-api
    environment:
      SIGNAL_API_URL: http://signal-api:8080
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  glucose-data:
  signal-data:
